apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aces-ml-chart.fullname" . }}-config
  labels:
    {{- include "aces-ml-chart.labels" . | nindent 4 }}
data:
  ML_MODEL_PATH: "/app/models/random_forest_model.joblib"
  LOG_LEVEL: "INFO"