apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aces-ml-chart.fullname" . }}
  labels:
    {{- include "aces-ml-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aces-ml-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "aces-ml-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aces-ml-chart.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python3"]
          args: ["-u", "/app/ML.py"]
          envFrom:
            - configMapRef:
                name: {{ include "aces-ml-chart.fullname" . }}-config
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: model-volume
              mountPath: /app/models
            - name: dataset-volume
              mountPath: /app
            - name: tmp-volume
              mountPath: /tmp
              readOnly: false
      volumes:
        - name: model-volume
          {{- if .Values.modelStorage.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "aces-ml-chart.fullname" . }}-model-pvc
          {{- else }}
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          {{- end }}
        - name: dataset-volume
          {{- if .Values.dataset.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "aces-ml-chart.fullname" . }}-dataset-pvc
          {{- end }}
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
