{{- if .Values.persistence.model.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aces-ml-chart.fullname" . }}-model
  labels:
    {{- include "aces-ml-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.model.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.model.size }}
---
{{- end }}
{{- if .Values.persistence.dataset.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aces-ml-chart.fullname" . }}-dataset
  labels:
    {{- include "aces-ml-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.dataset.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataset.size }}
{{- end }}