apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aces-ml.fullname" . }}
  labels:
    {{- include "aces-ml.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    kubernetes.io/change-cause: "Updated to match latest manifest configuration"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aces-ml.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aces-ml.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{ .Values.command }}
          {{- end }}
          {{- if .Values.args }}
          args: {{ .Values.args }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: {{ .Values.service.protocol }}
          env:
            - name: ML_MODEL_PATH
              value: "/app/models/model_files/random_forest_model.joblib"
            - name: LOG_LEVEL
              value: "INFO"
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_APP
              value: "ML.py"
            - name: PYTHONUNBUFFERED
              value: "1"
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: model-volume
              mountPath: /app/models
            - name: dataset-volume
              mountPath: /app/data
            - name: backup-volume
              mountPath: /app/csv_backups
            - name: tmp-volume
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: model-volume
          {{- if .Values.persistence.model.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "aces-ml.fullname" . }}-model
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: dataset-volume
          {{- if .Values.persistence.dataset.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "aces-ml.fullname" . }}-dataset
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: backup-volume
          emptyDir: {}
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.temporaryStorage.sizeLimit }}
