apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aces-ml.fullname" . }}
  labels:
    {{- include "aces-ml.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aces-ml.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aces-ml.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{ .Values.command }}
          {{- end }}
          {{- if .Values.args }}
          args: {{ .Values.args }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: ML_MODEL_PATH
              value: "/app/models/model_files/random_forest_model.joblib"
            - name: LOG_LEVEL
              value: "INFO"
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_APP
              value: "ML.py"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: model-volume
              mountPath: /app/models
            - name: dataset-volume
              mountPath: /app/data
            - name: tmp-volume
              mountPath: /tmp
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
      volumes:
        - name: model-volume
          {{- if .Values.persistence.model.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "aces-ml.fullname" . }}-model
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: dataset-volume
          {{- if .Values.persistence.dataset.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "aces-ml.fullname" . }}-dataset
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.temporaryStorage.sizeLimit }}
