apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aces-ml.fullname" . }}
  labels:
    {{- include "aces-ml.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "aces-ml.fullname" . }}
                port:
                  number: {{ .Values.service.port }}