# Default values for aces-ml.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sami4rhimi/aces-ml
  tag: "1.0.7"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  name: aces-ml
  selector:
    app: aces-ml
  port: 80
  targetPort: 8080
  protocol: TCP
  
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  model:
    enabled: true
    size: 2Gi
    accessMode: ReadWriteOnce
  dataset:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce

temporaryStorage:
  sizeLimit: 512Mi
  


