# Default values for aces-ml.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sami4rhimi/aces-ml
  tag: "1.0.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  protocol: TCP


ingress:
  enabled: true
  path: /
  pathType: Prefix
  className: webapprouting.kubernetes.azure.com
  host: aces-ml.172.189.152.57.nip.io
  annotations:
    kubernetes.azure.com/static-ip: "true"
    kubernetes.azure.com/backend-protocol: "https"
    kubernetes.azure.com/ssl-redirect: "true"
    kubernetes.azure.com/enable-caching: "true"
    kubernetes.azure.com/caching: "true"
    kubernetes.azure.com/health-probe: "true"
    kubernetes.azure.com/health-probe-path: "/health"
    kubernetes.azure.com/health-probe-interval: "30"
    kubernetes.azure.com/health-probe-timeout: "30"
    kubernetes.azure.com/health-probe-healthy-threshold: "2"
    kubernetes.azure.com/health-probe-unhealthy-threshold: "5"
    kubernetes.azure.com/health-probe-protocol: "https"
    nginx.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: webapprouting.kubernetes.azure.com


resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  model:
    enabled: true
    size: 2Gi
    accessMode: ReadWriteOnce
  dataset:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce

temporaryStorage:
  sizeLimit: 512Mi
  


