apiVersion: apps/v1
kind: Deployment
metadata:
  name: aces-ml
  namespace: aces-ml
  labels:
    app: aces-ml
    app.kubernetes.io/instance: aces-ml
    app.kubernetes.io/name: aces-ml
  annotations:
    kubernetes.io/change-cause: "Updated to handle CSV column count inconsistencies"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aces-ml
      app.kubernetes.io/instance: aces-ml
      app.kubernetes.io/name: aces-ml
  template:
    metadata:
      labels:
        app: aces-ml
        app.kubernetes.io/instance: aces-ml
        app.kubernetes.io/name: aces-ml
      annotations:
        checksum/config: "${RANDOM}"  # Force pod restart when config changes
    spec:
      initContainers:
        - name: init-dirs
          image: busybox
          command: ['sh', '-c', 'mkdir -p /app/data /app/models && chmod -R 777 /app/data /app/models']
          volumeMounts:
            - name: dataset-volume
              mountPath: /app/data
            - name: model-volume
              mountPath: /app/models
      containers:
        - name: aces-ml
          image: sami4rhimi/aces-ml:1.0.20  # Updated version
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "1500m"
              memory: "3Gi"
            requests:
              cpu: "750m"
              memory: "1.5Gi"
          volumeMounts:
            - name: dataset-volume
              mountPath: /app/data
            - name: model-volume
              mountPath: /app/models
            - name: backup-volume
              mountPath: /app/csv_backups
            - name: tmp-volume
              mountPath: /tmp
          env:
            - name: ML_MODEL_PATH
              value: "/app/models/random_forest_model.joblib"
            - name: DATASET_PATH
              value: "/app/data/final_dataset.csv"
            - name: MIN_SAMPLES_FOR_TRAINING
              value: "1"
            - name: BATCH_SIZE
              value: "5"
            - name: BATCH_TIMEOUT
              value: "1.0"
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aces-ml-secret
                  key: api-token
            - name: LOG_LEVEL
              value: "INFO"
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_APP
              value: "ML.py"
            - name: PYTHONUNBUFFERED
              value: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: dataset-volume
          persistentVolumeClaim:
            claimName: aces-ml-dataset
        - name: model-volume
          persistentVolumeClaim:
            claimName: aces-ml-model
        - name: backup-volume
          emptyDir: {}
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi