apiVersion: apps/v1
kind: Deployment
metadata:
  name: aces-ml
  namespace: aces-ml
  labels:
    app: aces-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aces-ml
  template:
    metadata:
      labels:
        app: aces-ml
    spec:
      containers:
        - name: aces-ml
          image: sami4rhimi/aces-ml:1.0.7
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: dataset-volume
              mountPath: /app/dataset/final_dataset.csv
              subPath: final_dataset.csv
            - name: model-volume
              mountPath: /app/models/model_files
            - name: tmp-volume
              mountPath: /tmp
          env:
            - name: ML_MODEL_PATH
              value: "/app/models/model_files/random_forest_model.joblib"
            - name: LOG_LEVEL
              value: "INFO"
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_APP
              value: "ML.py"
            - name: PYTHONUNBUFFERED
              value: "1"
      volumes:
        - name: dataset-volume
          persistentVolumeClaim:
            claimName: aces-ml-dataset
        - name: model-volume
          persistentVolumeClaim:
            claimName: aces-ml-model
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi