apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aces-ml
  namespace: aces-ml
  annotations:
    kubernetes.azure.com/static-ip: "true"
    kubernetes.azure.com/backend-protocol: "https"
    kubernetes.azure.com/ssl-redirect: "true"
    kubernetes.azure.com/enable-caching: "true"
    kubernetes.azure.com/caching: "true"
    kubernetes.azure.com/health-probe: "true"
    kubernetes.azure.com/health-probe-path: "/health"
    kubernetes.azure.com/health-probe-interval: "30"
    kubernetes.azure.com/health-probe-timeout: "30"
    kubernetes.azure.com/health-probe-healthy-threshold: "2"
    kubernetes.azure.com/health-probe-unhealthy-threshold: "5"
    kubernetes.azure.com/health-probe-protocol: "https"   
    nginx.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: webapprouting.kubernetes.azure.com
  labels:
    app: aces-ml
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
  - hosts:
    - aces-ml.172.189.152.57.nip.io
    secretName: aces-tls-secret
  rules:
  - host: aces-ml.172.189.152.57.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: aces-ml
            port: 
              number: 80
