apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aces-ml-model
  namespace: aces-ml
  labels:
    app: aces-ml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aces-ml-dataset
  namespace: aces-ml
  labels:
    app: aces-ml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi