apiVersion: v1
kind: ServiceAccount
metadata:
  name: aces-ml
  namespace: aces-ml
  labels:
    app: aces-ml
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
automountServiceAccountToken: false